CREATE_TABLE_TASK ="""
    CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task TEXT NOT NULL,
    completed INTEGER DEFAULT 0
    )
"""

INSERT_TASK = 'INSERT INTO tasks (task) VALUES (?)'

SELECT_TASK = 'SELECT id,task  FROM tasks'

DELETE_TASK = 'DELETE FROM tasks WHERE id = ?'

UPDATE_TASK = 'UPDATE tasks SET task = ? WHERE id = ?'

UPDATE_COMPLETED = 'UPDATE tasks SET completed = ? WHERE id = ?'

DELETE_ALL_TASK = 'DELETE  FROM tasks'